Create ranking view and slider on main page
Arashayo/TabletopHaven pull request #20
Opened 2024-02-11 15:50 UTC by gutek00714

## Related Issue
https://app.clickup.com/t/86bx8xz6n
https://app.clickup.com/t/86bxedhpu

## Changes list
Created ranking page (displays first 100 games)
Created slider on main page (right now working on 4 pictures located in public folder)

## Testing instructions

1. run node backend/src/createTables.js
2. run node backend/src/fillGames.js

## Screenshots (if appropriate):

2024-02-12 12:28 UTC, Amarczak001 requested changes

2024-02-12 12:28 UTC, Amarczak001 commented on frontend/src/components/Ranking.vue
> +  </style>
Everything has unnecessary TAB

2024-02-12 12:28 UTC, Amarczak001 commented on frontend/src/components/Ranking.vue
> +      <div class="main-site">
Unused class "main-site"

2024-02-18 18:49 UTC, Arashayo approved these changes

2024-02-18 20:55 UTC, closed without merging